CREATE DATABASE IF NOT EXISTS products;
CREATE DATABASE IF NOT EXISTS users;
CREATE DATABASE IF NOT EXISTS security;
CREATE DATABASE IF NOT EXISTS validation;
CREATE DATABASE IF NOT EXISTS cart;
CREATE DATABASE IF NOT EXISTS orders;

GRANT ALL PRIVILEGES ON products.* TO 'studi-jo'@'%';
GRANT ALL PRIVILEGES ON users.* TO 'studi-jo'@'%';
GRANT ALL PRIVILEGES ON security.* TO 'studi-jo'@'%';
GRANT ALL PRIVILEGES ON validation.* TO 'studi-jo'@'%';
GRANT ALL PRIVILEGES ON cart.* TO 'studi-jo'@'%';
GRANT ALL PRIVILEGES ON orders.* TO 'studi-jo'@'%';
FLUSH PRIVILEGES;
